---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rackops_rolebook]
  attributes:
    platformstack:
      omnibus_updater:
        enabled: false
      cloud_monitoring:
        enabled: false
      cloud_backup:
        enabled: false
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true
    rackspace_iptables:
      config:
        chains:
          INPUT: 
            '-s 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT':
              weight: 1000
              comment: 'vagrant ssh'
