name             'rackops_rolebook'
maintainer       'Rackspace, US Inc.'
maintainer_email 'rackspace-cookbooks@rackspace.com'
license          'All rights reserved'
description      'Installs/Configures rackops_rolebook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))

version          '2.0.2'

depends 'chef-client', '~> 3.5'
depends 'user', '~> 0.3'
depends 'motd-tail', '~> 2.0'
depends 'sudo', '~> 2.6'
depends 'ntp', '~> 1.6'
depends 'rackspace_iptables', '~> 1.2'
depends 'openssh', '~> 1.3'
depends 'rackspace_cloudmonitoring', '~> 4.0'
depends 'ohai', '~> 2.0'
depends 'apt', '~> 2.4'
depends 'yum', '~> 3.2'
